create table public.numbered_documents (
  id bigint generated by default as identity (
    start with 1000
    increment by 5
    minvalue 1000
    maxvalue 999999
    cache 20
    cycle
  ) primary key,
  title text not null
);
