import { cpSync, copyFileSync, lstatSync, mkdirSync, readFileSync } from "node:fs";
import { basename, join } from "node:path";
import { requireNoSchemaChanges } from "./assertions.mts";
import {
  runActionTask,
  runCommandTask,
  runSupabase,
  skippedCommand,
} from "./commands.mts";
import {
  captureGeneratedFiles,
  removeGeneratedSchema,
  removeMigrationSqlFiles,
  requirePathInside,
} from "./files.mts";
import { requiresFallback } from "./status.mts";
import type {
  CaseRunContext,
  CommandResult,
  GeneratedFile,
  ProjectResult,
  SnapshotCase,
} from "./types.mts";

export async function runSnapshotCase(
  migrationCase: SnapshotCase,
  context: CaseRunContext,
): Promise<ProjectResult> {
  const { config, runDirectory, caseIndex } = context;
  const sourceMigration = join(config.migrationsDirectory, migrationCase.fileName);
  const workProject = join(runDirectory, basename(migrationCase.name));
  const workMigrations = join(workProject, "supabase", "migrations");
  requirePathInside(runDirectory, workProject);
  requirePathInside(config.migrationsDirectory, sourceMigration);
  requirePathInside(workProject, workMigrations);
  const sourceMetadata = lstatSync(sourceMigration);
  if (!sourceMetadata.isFile() || sourceMetadata.isSymbolicLink()) {
    throw new Error(`Unsafe migration case: ${sourceMigration}`);
  }
  const migrationSql = readFileSync(sourceMigration, "utf8").trim();
  cpSync(config.runtimeTemplateDirectory, workProject, {
    recursive: true,
    errorOnExist: true,
  });
  mkdirSync(workMigrations);
  copyFileSync(sourceMigration, join(workMigrations, "20260101000000_case.sql"));

  let reset: CommandResult | undefined;
  if (caseIndex > 0) {
    reset = await runCommandTask(config, "Reset the database from this case's migration", () =>
      runSupabase(config, workProject, [
        "supabase",
        "db",
        "reset",
        "--local",
        "--no-seed",
        "--debug",
      ]),
    );
  }

  const generateCommand = [
    "supabase",
    "db",
    "schema",
    "declarative",
    "generate",
    "--local",
    ...(caseIndex === 0 ? ["--reset"] : []),
    "--overwrite",
    "--debug",
  ];
  const generate = await runCommandTask(
    config,
    "Generate a declarative schema from the migration",
    () =>
      reset?.status === "ERROR"
        ? skippedCommand(
            `npx ${generateCommand.join(" ")}`,
            "Database reset failed, so declarative generation was skipped.",
          )
        : runSupabase(config, workProject, generateCommand),
  );

  let legacyGenerate: CommandResult | undefined;
  let nextGeneratedFiles: GeneratedFile[] | undefined;
  let legacyGeneratedFiles: GeneratedFile[] | undefined;
  if (requiresFallback(generate)) {
    nextGeneratedFiles = captureGeneratedFiles(workProject);
    await runActionTask(
      "Capture files generated by pg-delta next",
      () => nextGeneratedFiles?.length ?? 0,
      (count) => `${count} file(s)`,
    );
  }

  const syncCommand = ["supabase", "db", "schema", "declarative", "sync", "--debug"];
  const syncVerificationCommand = [...syncCommand.slice(0, -1), "--no-apply", "--debug"];
  let sync = skippedCommand(
    `npx ${syncCommand.join(" ")}`,
    "Generate failed, so declarative sync was skipped.",
  );
  let migrationRemovalError: string | undefined;
  if (generate.status === "OK" || generate.status === "WARNING") {
    const migrationRemoval = await runActionTask(
      "Remove migration SQL from the working copy",
      () => removeMigrationSqlFiles(workProject),
      (count) => `${count} file(s) removed`,
    );
    if (migrationRemoval.status === "ERROR") {
      migrationRemovalError = migrationRemoval.error;
    }

    sync = await runCommandTask(
      config,
      "Generate a migration from the declarative schema (pg-delta next)",
      async () => {
        const result = await runSupabase(config, workProject, syncCommand);
        if (migrationRemovalError) {
          result.output = [
            `Migration cleanup failed before sync: ${migrationRemovalError}`,
            result.output,
          ]
            .filter(Boolean)
            .join("\n");
          result.status = "ERROR";
        }
        return result;
      },
    );
  } else {
    sync = await runCommandTask(
      config,
      "Generate a migration from the declarative schema (pg-delta next)",
      () => sync,
    );
  }

  let legacySync: CommandResult | undefined;
  let legacySyncVerification: CommandResult | undefined;
  let syncVerification: CommandResult | undefined;
  if (sync.status !== "ERROR") {
    syncVerification = await runCommandTask(
      config,
      "Confirm the declarative schema has no remaining changes",
      async () =>
        requireNoSchemaChanges(
          await runSupabase(config, workProject, syncVerificationCommand),
        ),
    );
  }

  if (generate.status === "WARNING" || generate.status === "ERROR") {
    removeGeneratedSchema(workProject);
    const legacyGenerateCommand = generateCommand.filter((argument) => argument !== "--reset");
    legacyGenerate = await runCommandTask(
      config,
      "Retry schema generation with pg-delta legacy",
      () => runSupabase(config, workProject, legacyGenerateCommand, "legacy"),
    );
    legacyGeneratedFiles = captureGeneratedFiles(workProject);
    await runActionTask(
      "Capture files generated by pg-delta legacy",
      () => legacyGeneratedFiles?.length ?? 0,
      (count) => `${count} file(s)`,
    );
  }

  if (generate.status === "WARNING") {
    legacySync = await runCommandTask(
      config,
      "Generate a migration from the declarative schema (pg-delta legacy)",
      () => runSupabase(config, workProject, syncCommand, "legacy"),
    );
    if (legacySync.status !== "ERROR") {
      legacySyncVerification = await runCommandTask(
        config,
        "Confirm the legacy schema has no remaining changes",
        async () =>
          requireNoSchemaChanges(
            await runSupabase(config, workProject, syncVerificationCommand, "legacy"),
          ),
      );
    }
  }

  return {
    kind: "snapshot",
    name: migrationCase.name,
    migrationSql,
    reset,
    generate,
    nextGeneratedFiles,
    legacyGenerate,
    legacyGeneratedFiles,
    sync,
    syncVerification,
    legacySync,
    legacySyncVerification,
  };
}
