create table public.populated_column_changes (
  id bigint generated by default as identity primary key,
  immutable_value text not null,
  widening_value integer not null,
  defaulted_value text not null default 'before',
  nullable_value text
);
