create table public.no_op_convergence_guard (
  id bigint generated by default as identity primary key,
  payload text not null default 'stable'
);

comment on table public.no_op_convergence_guard is
  'An identical desired declaration must produce no migration.';
