create table public.grants_rls_guard (
  id bigint generated by default as identity primary key,
  owner_name text not null,
  payload text not null
);

alter table public.grants_rls_guard enable row level security;

create policy grants_rls_guard_select
on public.grants_rls_guard
for select
to authenticated
using (owner_name = current_user);

grant select, insert, update
on table public.grants_rls_guard
to authenticated;
