create table public.dependency_source (
  id bigint generated by default as identity primary key,
  raw_value bigint not null
);

create function public.dependency_scale(input_value bigint)
returns bigint
language sql
immutable
strict
parallel safe
as $$
  select input_value * 2
$$;

create view public.dependency_base as
select
  source_row.id,
  public.dependency_scale(source_row.raw_value) as scaled_value
from public.dependency_source as source_row;

create view public.dependency_left as
select
  base_row.id,
  base_row.scaled_value + 1 as branch_value
from public.dependency_base as base_row;

create view public.dependency_right as
select
  base_row.id,
  base_row.scaled_value - 1 as branch_value
from public.dependency_base as base_row;

create view public.dependency_leaf as
select
  left_row.id,
  left_row.branch_value as left_value,
  right_row.branch_value as right_value,
  left_row.branch_value + right_row.branch_value as combined_value
from public.dependency_left as left_row
join public.dependency_right as right_row using (id);
