create table public.populated_column_changes (
  id bigint generated by default as identity primary key,
  immutable_value text not null,
  widening_value bigint not null,
  defaulted_value text not null default 'after',
  nullable_value text not null,
  added_value text not null default 'backfilled'
);
